<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="PCSC" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ThaiIdCardAgent.Core\ThaiIdCardAgent.Core.csproj" />
  </ItemGroup>
</Project>